language: rust
cache: cargo
before_script:
- which rustfmt || rustup component add rustfmt
git:
  depth: 1
script: >
  cargo fmt -- --check
  && cargo build --verbose --all --no-default-features  --features "$FEATURES"
  && cargo test --verbose --all --no-default-features --features "$FEATURES"
rust:
  - stable
  - nightly
env:
  matrix:
    - FEATURES=''
    - FEATURES='binary'
matrix:
  allow_failures:
    - rust: nightly
